version: "3.8"

networks:
  web:
    external: true

volumes:
  letsencrypt:

services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: always
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=joeljacobstephen@gmail.com
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt
    networks: [web]

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    command: ["--label-enable", "--interval", "300", "--rolling-restart"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - com.centurylinklabs.watchtower.enable=false

  api:
    restart: always
    networks: [web, litxplore-network]
    ports: [] # Traefik only
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.services.api.loadbalancer.server.port=8000

      # CORS
      - traefik.http.middlewares.cors.headers.accesscontrolallowmethods=GET,POST,PUT,PATCH,DELETE,OPTIONS
      - traefik.http.middlewares.cors.headers.accesscontrolallowheaders=Authorization,Content-Type,Cache-Control,Pragma,Accept,Origin,Expires,expires,X-CSRF-Token
      - traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=https://litxplore.vercel.app,https://litxplore.tech,https://www.litxplore.tech,http://localhost:3000
      - traefik.http.middlewares.cors.headers.accesscontrolallowcredentials=true
      - traefik.http.middlewares.cors.headers.accesscontrolmaxage=100
      - traefik.http.middlewares.cors.headers.addvaryheader=true

      # --- HTTP Router (for HTTPS) ---
      - traefik.http.routers.api.rule=Host(`litxplore.tech`)
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.tls.certresolver=myresolver
      - traefik.http.routers.api.middlewares=cors

      # --- Enable Watchtower for this service ---
      - com.centurylinklabs.watchtower.enable=true
