version: "3.8"

networks:
  web:
    external: true

volumes:
  letsencrypt:

services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: always
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      ##todo add all the trusted ips for cloudflare
      - --entrypoints.websecure.forwardedheaders.trustedips=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=joeljacobstephen@gmail.com
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt
    networks: [web]

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    command: ["--label-enable", "--interval", "300", "--rolling-restart"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - com.centurylinklabs.watchtower.enable=false

  api:
    restart: always
    networks: [web, litxplore-network]
    ports: [] # Traefik only
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.services.api.loadbalancer.server.port=8000

      # CORS
      - traefik.http.middlewares.cors.headers.accesscontrolallowmethods=GET,POST,PUT,PATCH,DELETE,OPTIONS
      - traefik.http.middlewares.cors.headers.accesscontrolallowheaders=Authorization,Content-Type,Cache-Control,Pragma,Accept,Origin,Expires,expires,X-CSRF-Token
      - traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=https://litxplore.vercel.app,https://litxplore.tech,https://www.litxplore.tech,http://localhost:3000
      - traefik.http.middlewares.cors.headers.accesscontrolallowcredentials=true
      - traefik.http.middlewares.cors.headers.accesscontrolmaxage=100
      - traefik.http.middlewares.cors.headers.addvaryheader=true

      # Rate Limiting - Protect against abuse and DDoS
      # General API rate limit: 100 requests per minute with burst of 50
      - traefik.http.middlewares.api-ratelimit.ratelimit.average=100
      - traefik.http.middlewares.api-ratelimit.ratelimit.period=1m
      - traefik.http.middlewares.api-ratelimit.ratelimit.burst=50
      - traefik.http.middlewares.api-ratelimit.ratelimit.sourcecriterion.ipstrategy.depth=1

      # Strict rate limit for auth/sensitive endpoints: 10 requests per minute
      - traefik.http.middlewares.strict-ratelimit.ratelimit.average=10
      - traefik.http.middlewares.strict-ratelimit.ratelimit.period=1m
      - traefik.http.middlewares.strict-ratelimit.ratelimit.burst=5
      - traefik.http.middlewares.strict-ratelimit.ratelimit.sourcecriterion.ipstrategy.depth=1

      # Ultra-strict for upload/processing endpoints: 5 requests per minute
      - traefik.http.middlewares.upload-ratelimit.ratelimit.average=5
      - traefik.http.middlewares.upload-ratelimit.ratelimit.period=1m
      - traefik.http.middlewares.upload-ratelimit.ratelimit.burst=2
      - traefik.http.middlewares.upload-ratelimit.ratelimit.sourcecriterion.ipstrategy.depth=1

      # Security Headers
      - traefik.http.middlewares.security.headers.framedeny=true
      - traefik.http.middlewares.security.headers.contenttypenosniff=true
      - traefik.http.middlewares.security.headers.browserxssfilter=true
      - traefik.http.middlewares.security.headers.forcestsheader=true
      - traefik.http.middlewares.security.headers.stsincludesubdomains=true
      - traefik.http.middlewares.security.headers.stsseconds=31536000

      # --- Main API Router (General endpoints) ---
      - traefik.http.routers.api.rule=Host(`litxplore.tech`) && !PathPrefix(`/api/v1/auth`) && !PathPrefix(`/api/v1/documents/upload`) && !PathPrefix(`/api/v1/review/generate`)
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.tls.certresolver=myresolver
      - traefik.http.routers.api.middlewares=cors,security,api-ratelimit
      - traefik.http.routers.api.priority=1

      # --- Auth Router (Strict rate limiting) ---
      - traefik.http.routers.api-auth.rule=Host(`litxplore.tech`) && PathPrefix(`/api/v1/auth`)
      - traefik.http.routers.api-auth.entrypoints=websecure
      - traefik.http.routers.api-auth.tls.certresolver=myresolver
      - traefik.http.routers.api-auth.middlewares=cors,security,strict-ratelimit
      - traefik.http.routers.api-auth.priority=3

      # --- Upload/Processing Router (Ultra-strict rate limiting) ---
      - traefik.http.routers.api-uploads.rule=Host(`litxplore.tech`) && (PathPrefix(`/api/v1/documents/upload`) || PathPrefix(`/api/v1/review/generate`))
      - traefik.http.routers.api-uploads.entrypoints=websecure
      - traefik.http.routers.api-uploads.tls.certresolver=myresolver
      - traefik.http.routers.api-uploads.middlewares=cors,security,upload-ratelimit
      - traefik.http.routers.api-uploads.priority=2

      # --- Enable Watchtower for this service ---
      - com.centurylinklabs.watchtower.enable=true
