version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: litxplore_backend_dev
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DOCKER_ENV=true
      - BEHIND_PROXY=false
      - PRODUCTION=false
      - REDIS_HOST=redis
    depends_on:
      redis:
        condition: service_started
    volumes:
      - ./uploads:/app/uploads
      - ./app:/app/app # Mount source code for development
    restart: unless-stopped
    networks:
      - litxplore-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: litxplore_redis_dev
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - litxplore-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  redis_data:

networks:
  litxplore-network:
    driver: bridge
