version: "3.8"

services:
  api:
    image: ghcr.io/joeljacobstephen/litxplore-backend:latest
    container_name: litxplore_backend
    ports:
      - "8000:8000" # Only accessible from localhost as nginx proxies this
    env_file:
      - .env
    environment:
      - DOCKER_ENV=true
      - BEHIND_PROXY=true
      - PRODUCTION=true
      - REDIS_HOST=redis
    depends_on:
      redis:
        condition: service_started
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    networks:
      - litxplore-network
    # Ensure consistent UID/GID for container user matches appuser in Dockerfile
    user: "1000:1000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: litxplore_redis
    # Don't expose redis port in production for security
    # ports:
    #   - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - litxplore-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  redis_data:

networks:
  litxplore-network:
    driver: bridge
