version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: litxplore-backend:latest
    container_name: litxplore_backend
    ports:
      - "8000:8000"  # Only accessible from localhost as nginx proxies this
    env_file:
      - .env
    environment:
      - DOCKER_ENV=true
      - BEHIND_PROXY=true
      - PRODUCTION=true
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-litxplore_db}
      - POSTGRES_HOST=db
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    networks:
      - litxplore-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-litxplore_db}
    # Don't expose postgres port in production for security
    # ports:
    #   - "5432:5432"  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - litxplore-network

  redis:
    image: redis:7-alpine
    # Don't expose redis port in production for security
    # ports:
    #   - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - litxplore-network

volumes:
  postgres_data:
  redis_data:

networks:
  litxplore-network:
    driver: bridge
